### ISSUE TITLE
✨ Add mutation tests

### ISSUE THREAD

**Issue by jossmoff** [jossmoff/bookshelf#5]
### Search before asking

- [X] I have searched in the [issues](https://github.com/jossmoff/bookshelf/issues?q=is%3Aissue) and found no similar issues.

### Description

We can use [mutmut](https://mutmut.readthedocs.io/en/latest/) to set up running mutation tests. We can run in the pipeline and set a threshold for an allowable mutation amount.

### Solution

Could use a workflow similar to below to run mutation tests when a certain label is added:

```yaml
name: Mutation Testing Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  mutation-tests:
    if: contains(github.event.pull_request.labels.*.name, 'mutation tests')
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v2

    - name: 🐍 Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify your desired Python version

    - name: 📦 Install dependencies
      run: pip install -r requirements-dev.txt  # Replace with your requirements file

    - name: ❄️ Run Flake8
      run: flake8 .

    - name: 🦠 Run unit tests
      run: mutmut run --CI
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
